Pull in changes fron Slycot Github actions; used F77EX instead of SLYCOT

diff --git a/.github/workflows/cibuildwheel.yml b/.github/workflows/cibuildwheel.yml
--- a/.github/workflows/cibuildwheel.yml
+++ b/.github/workflows/cibuildwheel.yml
@@ -1,33 +1,69 @@
-name: cibuildwheel for windows
+name: Build wheels
 
 on: [push, pull_request]
 
 jobs:
-  build_wheels:
+
+  build-sdist:
+    name: Build sdist
+    runs-on: ubuntu-latest
+    outputs:
+      sdist-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
+      sdist-name: ${{ steps.create-sdist.outputs.sdist }}
+
+    steps:
+      - name: Checkout source
+        uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+          submodules: 'recursive'
+
+      - name: Set up Python
+        uses: actions/setup-python@v6
+        with:
+          python-version: '3.14'
+
+      - name: Create sdist
+        id: create-sdist
+        run: |
+          pip install build
+          python -m build --sdist
+          [ $(find dist -type f|wc -l) -eq 1 ] || { echo "Expect 1 file in dist" 1>&2; exit 1; }
+          echo "sdist=$(find dist -type f)" >> "$GITHUB_ENV"
+          echo "sdist=$(find dist -type f -printf \"%f\")" >> "$GITHUB_OUTPUT"
+
+
+  build-wheels:
     name: Build wheels on ${{ matrix.os }}
+    needs: [build-sdist]
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [windows-latest]
+        os: [ubuntu-latest, macos-15-intel, windows-latest, ubuntu-24.04-arm,  macos-14]
     env:
-      CIBW_BUILD: "cp313-win_amd64"
-      MACOSX_DEPLOYMENT_TARGET: 14.0
+      CIBW_ENVIRONMENT: "CMAKE_ARGS='-DF77EX_BUNDLE_OPENBLAS=ON'"
+      CIBW_BUILD: "cp314-*"
 
     steps:
 
-      - uses: actions/checkout@v6
+      - name: Get sdist
+        uses: actions/download-artifact@v8
         with:
-          persist-credentials: false
+          artifact-ids: ${{ needs.build-sdist.outputs.sdist-id }}
 
       - uses: actions/setup-python@v6
+        with:
+          python-version: '3.14'
 
       - name: macos-config
         if: startsWith(matrix.os, 'macos')
-        # run a script that setups up commands slycot-gcc and slycot-gfortran
-        # these will be used in build and repair stages
         run: |
-          bash ./tools/cibw-setup-macos
-          echo SKBUILD_CMAKE_ARGS="-G Ninja;-DCMAKE_Fortran_COMPILER=slycot-gfortran;-DCMAKE_C_COMPILER=slycot-gcc" >> $GITHUB_ENV
+          set -x
+          gfortran_bin=$(command -v gfortran-13) || { echo "gfortran-13 not found" 1>&2; exit 1; }
+          gcc_bin=$(command -v gcc-13) || { echo "gcc-13 not found" 1>&2; exit 1; }
+          echo SKBUILD_CMAKE_ARGS="-G Ninja;-DCMAKE_Fortran_COMPILER=$gfortran_bin;-DCMAKE_C_COMPILER=$gcc_bin" >> $GITHUB_ENV
+          F77EX_LIBS=$($gfortran_bin -print-search-dirs|grep "^libraries: ="|sed s/^libraries:\ =//)
+          echo CIBW_ENVIRONMENT="F77EX_LIBS=$F77EX_LIBS $CIBW_ENVIRONMENT" >> "$GITHUB_ENV"
 
       - name: macos-deployment-target-14
         if: startsWith(matrix.os, 'macos-14')
@@ -39,17 +75,14 @@ jobs:
 
       - name: windows-config
         if: startsWith(matrix.os, 'windows')
-        # TODO: equivalent of command -v for gcc, gfortran
         run: |
           echo SKBUILD_CMAKE_ARGS="-G Ninja;-DCMAKE_Fortran_COMPILER=c:/mingw64/bin/gfortran.exe;-DCMAKE_C_COMPILER=c:/mingw64/bin/gcc.exe" >> $env:GITHUB_ENV
-
       - name: Install cibuildwheel
         run: python -m pip install cibuildwheel==3.3.1
 
       - name: Build wheels
         run: |
-          echo SKBUILD_CMAKE_ARGS: $SKBUILD_CMAKE_ARGS
-          python -m cibuildwheel --output-dir wheelhouse
+          python -m cibuildwheel --output-dir wheelhouse ${{ needs.build-sdist.outputs.sdist-name }}
 
       - uses: actions/upload-artifact@v6
         with:
